language: c
script:
  - bash merge-upstream.sh
env:
  global:
    secure: P+nwez8eB65Pex0hN9YeK7NdK0YEDYuflTCU4qI89jyHSHQzOtJomQ6yMW1M7QguRSk79clNMEOOar0zxwDm20opub9yyKaDj/NJm5fXGR3AxrtOKRQk8O6ilGgTMWLP9Os8bpEh6c+VgGjJ+VRkrMLZiKH8JngEAiNeJhY0+cGUmOXATobTdb+ePour41UEkh3VFbbQLEBlDLx84eazXhkEOuueUIDAxA4To7N0niTzPxAznFneSJ79zxJfWnJhFV2SwQDBtF8WWIwwiXOSmbFnJTrPKH+NvuAEwGMslhbpF3pj2HEnf9aSmFXWgNRX4ujJYwWN6awJTk62GzCVSoMwokT6jWZdQeKamZSumx3nI2f2a2nvzpQy2+fqXZwWZWD5roOMOHBXOlpNYn4y2xOU2iUvZ56sHJZWLYOSr5QXljx9IJg8Rp+eHewLuIz5/wO+vFkalmC38Yjnn4IU/OdOMJRaleGLlHAqTm7LNexCg/s7C964PjAlM0+3GrWLNYuWVBZ6oGMccjV808NQskHjBzXq9nZ0c6nqCQGTen+UGgWgoiWrxJFb5A9UvfVLbag+F6TzABeb8YXJOhyxgx6ZbmtwCNdEzMRv2Jd2+OkwmxjW7w0PwhE9z4YiTv9ysdaqA9DrxZf7C51pIdjFs/ogpsrzzwCrwF+lfXUMIqU=
